services:
  - type: web
    name: blockchain-verifier
    healthCheckPath: /health
    healthCheckTimeoutSeconds: 30
    envVars:
      - key: PORT
        value: "10000"
      - key: ENVIRONMENT
        value: "production"