name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -c "import hashlib; print(hashlib.sha256(b'test').hexdigest())" > test.txt
        python validate.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t blockchain-verifier:latest -f Dockerfile.prod .
    - name: Test Docker image
      run: |
        docker run -d -p 10000:10000 --name blockchain-verifier blockchain-verifier:latest
        sleep 5
        curl -f http://localhost:10000/health || exit 1

  # Uncomment and configure for actual deployment
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Deploy to production
  #     run: |
  #       # Add your deployment commands here
  #       echo "Deploying to production..."